# Generated by Django 3.2.16 on 2024-12-27 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20241227_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 11, 10, 52, 935211, tzinfo=utc), verbose_name='Дата и время регистрации'),
        ),
    ]
