# Generated by Django 3.2.16 on 2024-12-29 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20241229_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 15, 0, 0, 453693, tzinfo=utc), verbose_name='Дата и время регистрации'),
        ),
    ]
