# Generated by Django 3.2.16 on 2024-12-30 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_userprofile_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации комментария'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 8, 13, 17, 779106, tzinfo=utc), verbose_name='Дата и время регистрации'),
        ),
    ]
