# Generated by Django 3.2.16 on 2025-01-01 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20241230_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default=None, max_length=60, verbose_name='почта'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 17, 56, 45, 418830, tzinfo=utc), verbose_name='Дата и время регистрации'),
        ),
    ]
