# Generated by Django 3.2.16 on 2025-01-04 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20250101_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время регистрации'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default=None, max_length=60, verbose_name='Адрес электронной почты'),
        ),
    ]
