# Generated by Django 3.2.16 on 2025-01-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20250105_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
